Fix card's style
kendraio/kendraio-app pull request #408
Opened 2023-11-09 13:41 UTC by gsambrotta

- remove padding around image
- make image take all the container's space
- move card style in card style's component
- add truncate helper class and documentation in style.scss

2023-11-09 16:48 UTC, CodeKrakken requested changes
Just one comment on the English text. Otherwise no problems - looks very nice!

2023-11-09 16:48 UTC, CodeKrakken commented on src/styles/main.scss
> +*********/
A few grammar/spelling bits here. Here's a corrected version:

Global style guide
_ If a block is nested or the HTML is generated, the style will not be applicable to the component style and will need to be written here.
_ There are some helper classes below. Search for "HELPER CLASS" to find them.
_ The style attribute does not work on the HTML block, as the HTML is sanitised. If you need to style a specific HTML tag, you can add a class for the style here.

2023-11-10 10:13 UTC, lukestanley commented on src/styles/main.scss
> +_ The style attribute does not work on the HTML block, as the HTML is sanitize. If is needed to style a specific HTML tag, is possible to add a class and add the style here.
```suggestion
/*********
Global Style Guide:
- Styles not applicable directly within component styles should go here.
- Helper classes are listed below. They are usable within sanitised
  HTML and are marked as "HELPER CLASS" for easy identification.
- Helper classes are particularly useful with the Template block, 
  where the style attribute is sanitised, but CSS classes are allowed.
*********/
```
This is more clear and concise. @gsambrotta

2023-11-10 10:14 UTC, lukestanley approved these changes
Approved with a suggested change for the big comment.

2023-11-15 12:22 UTC, CodeKrakken approved these changes

2023-11-15 12:24 UTC, merged