Build the update version of the documentation
kendraio/kendraio-app pull request #460
Opened 2024-03-18 12:02 UTC by gsambrotta

In the past months we have improved and fix our documentation but we forget to build it so the edit are not visible in production.
In this PR I:
- built the documentation 
- I added some required packages to the python package manager  
- I fix some page of the doc taht did not look good. 

To see if it works you can run the documentation on your local with the command `sphinx-autobuild docs/ docs/_build/html`
and then access the documentation at `http://127.0.0.1:8000`

If you get some error, please refer to the doc to see if you have installed all the required libraries to run the doc:  https://kendraio-app.readthedocs.io/en/latest/documentation.html

2024-03-18 12:53 UTC, CodeKrakken requested changes
A couple of minor syntax changes.

2024-03-18 12:53 UTC, CodeKrakken commented on docs/workflow/blocks/mapping.rst
> +Hardcoded string's value must be wrapped in backticks, otherwise it will result `null` for undefined variables.
Minor syntax changes - 

"A hardcoded string's value must be wrapped in backticks, otherwise it will result in `null` for undefined variables."

2024-03-18 12:53 UTC, CodeKrakken commented on docs/workflow/blocks/mapping.rst
> +Is also possible to wrap a whole JSON object in backticks:
Minor syntax change -

"It is also possible to wrap a whole JSON object in backticks:"

2024-03-18 22:15 UTC, lukestanley commented
It's nice to be able to see updates to the docs locally I suppose. I thought that there is an auto-build that happens on GitHub when main is updated, or develop possibly, but I need to check. 
What does the added package do better? Is it a UI improvement that helps local builds?

2024-03-21 17:12 UTC, gsambrotta commented
> It's nice to be able to see updates to the docs locally I suppose. I thought that there is an auto-build that happens on GitHub when main is updated, or develop possibly, but I need to check. What does the added package do better? Is it a UI improvement that helps local builds?

Do you mean `sphinx_rtd_theme` https://github.com/kendraio/kendraio-app/pull/460/files#diff-2c9c11d26b09b8afde329980309d967121543a456e4592c76886a20b5cf56c90R3? Is not a new package. It is required for autobuilding the documentation while developing. It is in the documentation, but was not part of the package manager file.

2024-03-28 13:44 UTC, gsambrotta commented
@CodeKrakken I have fix the typo as you suggested. Can you please review it again?

@lukestanley Do you know where and how the documentation is hosted? We need to see where the documentation building command is, as it is not updating

2024-03-28 13:50 UTC, gsambrotta commented
Here it is: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/read-the-docs.html
We should have an account tin readthedocs.io

2024-03-28 14:49 UTC, CodeKrakken requested changes
Just one more change to make - sorry!

2024-03-28 14:49 UTC, CodeKrakken commented on docs/workflow/blocks/launch_block.rst
> +- **context** - Data that will be pass to the flow to launch
Small syntax change - Data that will be passed to the flow to launch

2024-03-29 10:47 UTC, gsambrotta commented
@CodeKrakken ready again :D

2024-04-02 17:08 UTC, CodeKrakken approved these changes
No problems here.

2024-04-03 14:00 UTC, gsambrotta commented
@CodeKrakken ready again :)

2024-04-03 14:34 UTC, CodeKrakken commented
@gsambrotta I approved this yesterday and I can't see any further changes. Have I missed something? Cheers!

2024-04-03 18:35 UTC, gsambrotta commented
@CodeKrakken sorry, my page didn't update. All good!

2024-04-03 18:35 UTC, merged